<?php
return [
    '/' => 'auth/index.php',
    '/login' => 'auth/login.php',
    '/register' => 'auth/register.php',
    '/logout' => 'auth/logout.php',
    '/dashboard' => 'admin/dashboard.php',
    '/admin/home' => ['controller' => 'admin/dashboard.php', 'page' => 'home'],
    '/admin/users' => ['controller' => 'admin/dashboard.php', 'page' => 'user'],
    '/admin/users/create' => ['controller' => 'admin/dashboard.php', 'page' => 'user_tambah'],
    '/admin/users/edit' => ['controller' => 'admin/dashboard.php', 'page' => 'user_ubah'],
    '/admin/customers' => ['controller' => 'admin/dashboard.php', 'page' => 'pelanggan'],
    '/admin/customers/detail' => ['controller' => 'admin/dashboard.php', 'page' => 'pelanggan_detail'],
    '/admin/customers/create' => ['controller' => 'admin/dashboard.php', 'page' => 'pelanggan_tambah'],
    '/admin/customers/edit' => ['controller' => 'admin/dashboard.php', 'page' => 'pelanggan_ubah'],
    '/admin/products' => ['controller' => 'admin/dashboard.php', 'page' => 'produk'],
    '/admin/products/create' => ['controller' => 'admin/dashboard.php', 'page' => 'produk_tambah'],
    '/admin/products/edit' => ['controller' => 'admin/dashboard.php', 'page' => 'produk_ubah'],
    '/admin/settings' => ['controller' => 'admin/dashboard.php', 'page' => 'settings'],
    '/admin/sales' => ['controller' => 'admin/dashboard.php', 'page' => 'pembelian'],
    '/admin/sales/detail' => ['controller' => 'admin/dashboard.php', 'page' => 'penjualan_detail'],
    '/admin/checkout' => ['controller' => 'admin/dashboard.php', 'page' => 'checkout'],
    '/admin/sales/create' => ['controller' => 'admin/dashboard.php', 'page' => 'pembelian_tambah'],
    '/admin/cashiers' => 'admin/cashiers_redirect.php',
    '/admin/cashiers/create' => 'admin/cashiers_redirect.php',
    '/admin/cashiers/edit' => 'admin/cashiers_redirect.php',
    '/receipt' => 'admin/cetak_struk.php',
    '/receipt/print' => ['view' => 'admin/struk_makan.php'],
    '/admin/export' => 'admin/download_data_pemb_excel.php',
    '/admin/sales/status' => 'admin/penjualan_status_update.php',
    '/admin/sales/delete' => 'admin/penjualan_hapus.php',
    '/admin/customers/delete' => 'admin/pelanggan_hapus.php',
    '/admin/products/delete' => 'admin/produk_hapus.php',
    '/admin/users/delete' => 'admin/user_hapus.php',
    '/admin/cashiers/delete' => 'admin/cashiers_redirect.php',
    '/admin/cart/clear' => 'admin/cart_hapus.php',
    '/api/products/search' => 'api/search_produk.php',
    '/shop' => 'storefront/user_home.php',
    '/products' => 'storefront/user_produk.php',
    '/product' => 'storefront/user_produk_detail.php',
    '/cart' => 'storefront/keranjang.php',
    '/cart/add' => 'storefront/keranjang_tambah.php',
    '/cart/update' => 'storefront/keranjang_ubah.php',
    '/cart/remove' => 'storefront/keranjang_hapus.php',
    '/checkout' => 'storefront/checkout.php',
    '/checkout/customer' => 'storefront/user_checkout.php',
    '/orders' => 'storefront/pesanan.php',
    '/orders/detail' => 'storefront/pesanan_detail.php',
    '/profile' => 'storefront/profile.php',
];
