<?php
require_once APP_ROOT . '/app/Support/user_helpers.php';
user_require_customer();
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT); if (!$id) user_redirect('pesanan.php'); $id_user = (int) $_SESSION['id_user'];
$stmt = mysqli_prepare($koneksi, 'SELECT p.*, pl.nama_pelanggan, pl.alamat, pl.no_telepon FROM penjualan p LEFT JOIN pelanggan pl ON pl.id_pelanggan = p.id_pelanggan WHERE p.id_penjualan = ? AND p.id_kasir = ? LIMIT 1'); mysqli_stmt_bind_param($stmt, 'ii', $id, $id_user); mysqli_stmt_execute($stmt); $order = mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));
if (!$order) { http_response_code(404); exit('Pesanan tidak ditemukan.'); }
$detail_stmt = mysqli_prepare($koneksi, 'SELECT d.jumlah_produk, d.sub_total, p.nama_produk FROM detail_penjualan d LEFT JOIN produk p ON p.id_produk = d.id_produk WHERE d.id_penjualan = ?'); mysqli_stmt_bind_param($detail_stmt, 'i', $id); mysqli_stmt_execute($detail_stmt); $details = mysqli_stmt_get_result($detail_stmt); $page_title = 'Detail pesanan #' . $id; $active_page = 'pesanan'; include APP_ROOT . '/resources/views/storefront/header.php';
?>
<div class="page-title"><h1>Pesanan #<?= (int) $order['id_penjualan']; ?></h1><div class="muted"><?= e(date('d F Y', strtotime($order['tanggal_penjualan']))); ?></div></div><div class="checkout-layout"><section class="panel"><h2>Produk</h2><?php while ($item = mysqli_fetch_assoc($details)): ?><div class="cart-total" style="border-top:0;margin:0;padding:12px 0;font-size:.95rem"><span><?= e($item['nama_produk'] ?: 'Produk'); ?> x <?= (int) $item['jumlah_produk']; ?></span><strong><?= user_money($item['sub_total']); ?></strong></div><?php endwhile; ?><div class="cart-total"><span>Total</span><span><?= user_money($order['total_harga']); ?></span></div></section><aside class="panel"><h2>Status pesanan</h2><p><span class="status <?= in_array($order['status'], ['Proses', 'Dibatalkan'], true) ? 'process' : ''; ?>"><?= e(user_order_status_label($order['status'])); ?></span></p><p class="muted">Pembayaran: <strong><?= e($order['metode'] ?: 'Cash'); ?></strong></p><hr><h2>Alamat pengiriman</h2><p><strong><?= e($order['nama_pelanggan']); ?></strong><br><?= nl2br(e($order['alamat'])); ?><br><?= e($order['no_telepon']); ?></p></aside></div>
<?php include APP_ROOT . '/resources/views/storefront/footer.php'; ?>
